package com.principal;

import javax.swing.JOptionPane;

/**
 *
 * @author hanse
 */
public class InterfazParticipante extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazParticipante.class.getName());

    /**
     * Creates new form InterfazParticipante
     */
    ProcesarDatos datos = new ProcesarDatos();
    public InterfazParticipante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plBackground = new javax.swing.JPanel();
        lblCuatrimestre = new javax.swing.JLabel();
        separador2 = new javax.swing.JSeparator();
        lblTitulo = new javax.swing.JLabel();
        lbMatricula = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        txtNombres = new javax.swing.JTextField();
        separador3 = new javax.swing.JSeparator();
        txtApellidos = new javax.swing.JTextField();
        separador4 = new javax.swing.JSeparator();
        txtCuatrimestre = new javax.swing.JTextField();
        separador5 = new javax.swing.JSeparator();
        btnPresentar = new javax.swing.JButton();
        btnCapturar = new javax.swing.JButton();
        lbImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos Estudiante");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plBackground.setBackground(new java.awt.Color(255, 255, 255));
        plBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCuatrimestre.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCuatrimestre.setForeground(new java.awt.Color(0, 0, 51));
        lblCuatrimestre.setText("Cuatrimestre:");
        plBackground.add(lblCuatrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, 40));

        separador2.setForeground(new java.awt.Color(204, 204, 204));
        plBackground.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 150, 20));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 0, 51));
        lblTitulo.setText("Datos Estudiante");
        plBackground.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 17, -1, 30));

        lbMatricula.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lbMatricula.setForeground(new java.awt.Color(0, 0, 51));
        lbMatricula.setText("Matricula:");
        plBackground.add(lbMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, 40));

        lblNombres.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(0, 0, 51));
        lblNombres.setText("Nombres:");
        plBackground.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, 40));

        lblApellidos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(0, 0, 51));
        lblApellidos.setText("Apellidos:");
        plBackground.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, 40));

        txtMatricula.setBackground(new java.awt.Color(255, 255, 255));
        txtMatricula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtMatricula.setText("Escribir matricula");
        txtMatricula.setBorder(null);
        txtMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMatriculaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMatriculaFocusLost(evt);
            }
        });
        plBackground.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 150, 30));

        separador1.setForeground(new java.awt.Color(204, 204, 204));
        plBackground.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 480, 20));

        txtNombres.setBackground(new java.awt.Color(255, 255, 255));
        txtNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombres.setText("Escribir nombres");
        txtNombres.setBorder(null);
        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        plBackground.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 150, 30));

        separador3.setForeground(new java.awt.Color(204, 204, 204));
        plBackground.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 150, 20));

        txtApellidos.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtApellidos.setText("Escribir apellidos");
        txtApellidos.setBorder(null);
        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        plBackground.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, 30));

        separador4.setForeground(new java.awt.Color(204, 204, 204));
        plBackground.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, 20));

        txtCuatrimestre.setBackground(new java.awt.Color(255, 255, 255));
        txtCuatrimestre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCuatrimestre.setText("Escribir cuatrimestre");
        txtCuatrimestre.setBorder(null);
        txtCuatrimestre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCuatrimestreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCuatrimestreFocusLost(evt);
            }
        });
        txtCuatrimestre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuatrimestreKeyTyped(evt);
            }
        });
        plBackground.add(txtCuatrimestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 150, 30));

        separador5.setForeground(new java.awt.Color(204, 204, 204));
        plBackground.add(separador5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 20));

        btnPresentar.setBackground(new java.awt.Color(0, 0, 51));
        btnPresentar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPresentar.setForeground(new java.awt.Color(255, 255, 255));
        btnPresentar.setText("Presentar");
        btnPresentar.setBorder(null);
        btnPresentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresentarActionPerformed(evt);
            }
        });
        plBackground.add(btnPresentar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 120, 40));

        btnCapturar.setBackground(new java.awt.Color(0, 0, 51));
        btnCapturar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapturar.setForeground(new java.awt.Color(255, 255, 255));
        btnCapturar.setText("Capturar");
        btnCapturar.setBorder(null);
        btnCapturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapturarActionPerformed(evt);
            }
        });
        plBackground.add(btnCapturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 120, 40));

        lbImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/principal/img/perfil.png"))); // NOI18N
        plBackground.add(lbImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        getContentPane().add(plBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtMatriculaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaFocusGained
        if(txtMatricula.getText().equals("Escribir matricula")) {
            txtMatricula.setText("");
        }
    }//GEN-LAST:event_txtMatriculaFocusGained

    private void txtMatriculaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMatriculaFocusLost
        if(txtMatricula.getText().trim().equals("")) {
            txtMatricula.setText("Escribir matricula");
        }
    }//GEN-LAST:event_txtMatriculaFocusLost

    private void txtNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusGained
        if(txtNombres.getText().equals("Escribir nombres")) {
            txtNombres.setText("");
        }
    }//GEN-LAST:event_txtNombresFocusGained

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost
        if(txtNombres.getText().trim().equals("")) {
            txtNombres.setText("Escribir nombres");
        }
    }//GEN-LAST:event_txtNombresFocusLost

    private void txtApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusGained
        if(txtApellidos.getText().equals("Escribir apellidos")) {
            txtApellidos.setText("");
        }
    }//GEN-LAST:event_txtApellidosFocusGained

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
        if(txtApellidos.getText().trim().equals("")) {
            txtApellidos.setText("Escribir apellidos");
        }
    }//GEN-LAST:event_txtApellidosFocusLost

    private void txtCuatrimestreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuatrimestreFocusGained
        if(txtCuatrimestre.getText().equals("Escribir cuatrimestre")) {
            txtCuatrimestre.setText("");
        }
    }//GEN-LAST:event_txtCuatrimestreFocusGained

    private void txtCuatrimestreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCuatrimestreFocusLost
        if(txtCuatrimestre.getText().trim().equals("")) {
            txtCuatrimestre.setText("Escribir cuatrimestre");
        }
    }//GEN-LAST:event_txtCuatrimestreFocusLost

    private void btnCapturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapturarActionPerformed
        if(!verificarDatos()) {
            return;
        }
        String matricula = txtMatricula.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        int cuatrimestre = Integer.parseInt(txtCuatrimestre.getText());
        
        datos.capturarDatos(matricula, nombres, apellidos, cuatrimestre);
        JOptionPane.showMessageDialog(this, "Datos guardados correctamente");
    }//GEN-LAST:event_btnCapturarActionPerformed

    private void txtCuatrimestreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuatrimestreKeyTyped
        char key = evt.getKeyChar();
        if(key < '0' || key > '9') {
            evt.consume();
        }
    }//GEN-LAST:event_txtCuatrimestreKeyTyped

    private void btnPresentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresentarActionPerformed
        String matricula = datos.getMatricula();
        String nombres = datos.getNombres();
        String apellidos = datos.getApellidos();
        int cuatrimestre = datos.getCuatrimestre();
        
        JOptionPane.showMessageDialog(this, "Datos del estudiante: \n"+"Matricula: "+datos.getMatricula()+
                "\nnombres: "+datos.getNombres()+"\nApellidos: "+datos.getApellidos()+
                "\nCuatrimestre: "+datos.getCuatrimestre());
    }//GEN-LAST:event_btnPresentarActionPerformed

    
    private boolean verificarDatos() {
        boolean estado = true;
        String matricula = txtMatricula.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String cuatrimestre = txtCuatrimestre.getText();
        
        if(matricula.isEmpty() || nombres.isEmpty() || apellidos.isEmpty() || cuatrimestre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Datos incompletos");
            estado = false;
        }
        
        return estado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazParticipante().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapturar;
    private javax.swing.JButton btnPresentar;
    private javax.swing.JLabel lbImg;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCuatrimestre;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel plBackground;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    private javax.swing.JSeparator separador5;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCuatrimestre;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
}
